---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mastodon-config
  labels:
    app: mastodon
data:
  # Postgres connection settings
  DB_HOST: postgres.default.svc.cluster.local
  DB_NAME: mastodon
  DB_PORT: '5432'
  DB_USER: mastodon

  # Redis connection settings
  REDIS_HOST: mastodon.default.svc.cluster.local
  REDIS_PORT: '6379'

  # Miscellaneous mastodon app configuration
  LOCAL_DOMAIN: example.org
  WEB_DOMAIN: example.org
  SINGLE_USER_MODE: 'false'
  DEFAULT_LOCALE: en

  # SMTP server settings for outbound mail
  SMTP_SERVER: smtp.mailgun.org
  SMTP_PORT: '465'
  SMTP_LOGIN: mastodon@example.org
  SMTP_FROM_ADDRESS: mastodon@example.org
  SMTP_DOMAIN: example.org
  SMTP_TLS: 'true'

  # S3 Paperclip settings for uploads
  S3_ENABLED: 'true'
  S3_BUCKET: example-mastodon
  S3_REGION: us-west-1
  S3_PROTOCOL: https
