---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mastodon-secrets
  labels:
    app: mastodon
data:
  # Postgres database password
  DB_PASS:

  # Secret values
  # Generate these three with `rake secret` inside a mastodon container
  SECRET_KEY_BASE:
  OTP_SECRET:
  PAPERCLIP_SECRET:

  # VAPID (push notification) keys
  # Generate with `RAILS_ENV=production bundle exec rake mastodon:webpush:generate_vapid_key` inside a mastodon container
  VAPID_PRIVATE_KEY:
  VAPID_PUBLIC_KEY:

  # SMTP server login password
  SMTP_PASSWORD:

  # AWS account credentials for S3 access
  AWS_ACCESS_KEY:
  AWS_SECRET_ACCESS_KEY:
